let token=parent.localStorage.getItem("mostakshef_token"),me,grades=[],units=[],lessons=[],quizzes=[],bank=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function H(){return {"Content-Type":"application/json",Authorization:"Bearer "+token}}
async function api(u,o={}){let r=await fetch(u,{...o,headers:{...H(),...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"حدث خطأ");return d}
function toast(x,type="ok"){const box=$("#aToast");box.className="toast "+type;box.textContent=x;box.classList.remove("hidden");clearTimeout(window.__toast);window.__toast=setTimeout(()=>box.classList.add("hidden"),2800)}
function closeModal(){const m=$("#modal");m.classList.add("hidden");$("#modalBody").innerHTML=""}
function openModal(x){$("#modalBody").innerHTML=x;$("#modal").classList.remove("hidden");setTimeout(()=>$("#modal input, #modal select, #modal textarea")?.focus(),30)}
function tab(t){$$('[data-page]').forEach(x=>x.classList.toggle('hidden',x.dataset.page!==t));$$('.adminSide button').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));if(t==='bank')renderBank()}
$$('.adminSide button').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
$("#modal")?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$("#modal").classList.contains('hidden'))closeModal()});
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function gradeName(id){return grades.find(x=>x.id===id)?.name||'—'} function unitName(id){return units.find(x=>x.id===id)?.name||'بدون وحدة'}
function gradeSelect(id='gradeId',required=true){return `<select id="${id}" ${required?'required':''}><option value="">اختر الصف</option>${grades.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('')}</select>`}
function setFilterOptions(){for(const id of ['unitGradeFilter','lessonGradeFilter','quizGradeFilter']){const el=$("#"+id);if(!el)continue;const old=el.value;el.innerHTML='<option value="">كل الصفوف</option>'+grades.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('');el.value=old}}
async function load(){
 [grades,units,lessons,quizzes]=await Promise.all([api('/api/grades'),api('/api/units'),api('/api/lessons'),api('/api/quizzes')]);
 setFilterOptions(); render();
 const s=await api('/api/admin/stats');
 $("#stats").innerHTML=Object.entries({طلاب:s.students,مدرسون:s.teachers,صفوف:s.grades,وحدات:s.units,دروس:s.lessons,اختبارات:s.quizzes,محاولات:s.attempts}).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join('');
}
function empty(title,sub){return `<div class="empty"><div class="emptyIcon">📭</div><h3>${title}</h3><p>${sub||''}</p></div>`}
function render(){renderGrades();renderUnits();renderLessons();renderQuizzes();if(me.role==='admin')renderUsers();}
function renderGrades(){const q=($("#gradeSearch")?.value||'').trim().toLowerCase(),stage=$("#gradeStageFilter")?.value||'';const a=grades.filter(g=>(!q||g.name.toLowerCase().includes(q))&&(!stage||g.stage===stage));$("#gradesList").innerHTML=a.length?a.map(g=>`<article class="card entityCard"><div class="entityTop"><span class="bigIcon">🎓</span><span class="tag">${g.stage==='primary'?'ابتدائي':'إعدادي'}</span></div><h3>${esc(g.name)}</h3><p>صف دراسي جاهز لإضافة الوحدات والدروس والاختبارات.</p>${me.role==='admin'?`<div class="actions"><button onclick="editGrade('${g.id}')">تعديل</button><button class="danger" onclick="deleteGrade('${g.id}')">حذف</button></div>`:''}</article>`).join(''):empty('لا توجد صفوف','اضغط «إضافة صف» لبدء بناء المنهج.')}
function renderUnits(){const q=($("#unitSearch")?.value||'').trim().toLowerCase(),gf=$("#unitGradeFilter")?.value||'';const a=units.filter(u=>(!q||u.name.toLowerCase().includes(q))&&(!gf||u.gradeId===gf));$("#unitsList").innerHTML=a.length?a.map(u=>`<article class="card entityCard"><div class="entityTop"><span class="bigIcon">📚</span><span class="tag">${esc(gradeName(u.gradeId))}</span></div><h3>${esc(u.name)}</h3><p>${esc(u.description||'بدون وصف')}</p><div class="actions"><button onclick="editUnit('${u.id}')">تعديل</button><button class="danger" onclick="delEntity('/api/admin/units/${u.id}','الوحدة')">حذف</button></div></article>`).join(''):empty('لا توجد وحدات','أضف وحدة جديدة واربطها بالصف المناسب.')}
function renderLessons(){const q=($("#lessonSearchAdmin")?.value||'').trim().toLowerCase(),gf=$("#lessonGradeFilter")?.value||'';const a=lessons.filter(l=>(!q||l.title.toLowerCase().includes(q))&&(!gf||l.gradeId===gf));$("#lessonsList").innerHTML=a.length?a.map(l=>`<article class="card entityCard"><div class="entityTop"><span class="bigIcon">📖</span><span class="tag">${esc(gradeName(l.gradeId))}</span></div><h3>${esc(l.title)}</h3><p>${esc(l.summary||'بدون ملخص')}</p><div class="metaLine">${l.youtubeId?'🎬 فيديو مرتبط':'📌 بدون فيديو'} · ${esc(unitName(l.unitId))}</div><div class="actions"><button onclick="editLesson('${l.id}')">تعديل</button><button class="danger" onclick="delEntity('/api/admin/lessons/${l.id}','الدرس')">حذف</button></div></article>`).join(''):empty('لا توجد دروس','أضف أول درس ليظهر للطلاب.')}
function renderQuizzes(){const q=($("#quizSearchAdmin")?.value||'').trim().toLowerCase(),gf=$("#quizGradeFilter")?.value||'';const a=quizzes.filter(x=>(!q||x.title.toLowerCase().includes(q))&&(!gf||x.gradeId===gf));$("#quizzesList").innerHTML=a.length?a.map(x=>`<article class="card entityCard"><div class="entityTop"><span class="bigIcon">📝</span><span class="tag">${esc(gradeName(x.gradeId))}</span></div><h3>${esc(x.title)}</h3><p>${x.questions.length} سؤال · نجاح من ${x.passingScore||50}%${x.duration?` · ${x.duration} دقيقة`:''}</p><div class="actions"><button onclick="editQuiz('${x.id}')">تعديل</button><button class="danger" onclick="delEntity('/api/admin/quizzes/${x.id}','الاختبار')">حذف</button></div></article>`).join(''):empty('لا توجد اختبارات','أضف اختبارًا واكتب أسئلته من نفس النافذة.')}
async function renderBank(){try{bank=await api('/api/question-bank');const q=($("#bankSearch")?.value||'').trim().toLowerCase();const a=bank.filter(x=>(!q||x.text.toLowerCase().includes(q)||x.quizTitle.toLowerCase().includes(q)));$("#bankList").innerHTML=a.length?a.map((x,i)=>`<article class="card"><span class="tag">${esc(gradeName(x.gradeId))}</span><h3>${i+1}. ${esc(x.text)}</h3><p>${esc(x.quizTitle)}</p><p class="muted">الإجابة الصحيحة: <b>${esc(x.options[x.answer]||'—')}</b></p></article>`).join(''):empty('لا توجد أسئلة','أنشئ اختبارًا وأضف إليه أسئلة.') }catch(e){toast(e.message,'error')}}
async function renderUsers(){let u=await api('/api/admin/users');$("#usersList").innerHTML=u.length?u.map(x=>`<article class="card"><h3>${esc(x.name)}</h3><p>${esc(x.email)}</p><p><span class="tag">${x.role==='admin'?'مدير':x.role==='teacher'?'مدرس':'طالب'}</span> ${x.gradeId?'— '+esc(gradeName(x.gradeId)):''}</p></article>`).join(''):empty('لا يوجد مستخدمون','');}
function openGrade(){openModal(`<div class="modalHead"><span class="bigIcon">🎓</span><div><h2>إضافة صف جديد</h2><p class="muted">سيظهر الصف فورًا في الموقع والاختيارات الخاصة بالمحتوى.</p></div></div><form onsubmit="saveGrade(event)"><label>اسم الصف<input id="n" placeholder="مثال: الصف الرابع الابتدائي" required maxlength="80"></label><label>المرحلة<select id="s"><option value="primary">ابتدائي</option><option value="preparatory">إعدادي</option></select></label><div class="formActions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button id="saveBtn" class="primaryAction">حفظ الصف ✓</button></div></form>`)}
function editGrade(id){const g=grades.find(x=>x.id===id);if(!g)return;openModal(`<div class="modalHead"><span class="bigIcon">✏️</span><div><h2>تعديل الصف</h2><p class="muted">غيّر البيانات ثم احفظ.</p></div></div><form onsubmit="saveGrade(event,'${id}')"><label>اسم الصف<input id="n" value="${esc(g.name)}" required maxlength="80"></label><label>المرحلة<select id="s"><option value="primary" ${g.stage==='primary'?'selected':''}>ابتدائي</option><option value="preparatory" ${g.stage==='preparatory'?'selected':''}>إعدادي</option></select></label><div class="formActions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button id="saveBtn" class="primaryAction">حفظ التعديلات ✓</button></div></form>`)}
async function saveGrade(e,id){e.preventDefault();const btn=$("#saveBtn");btn.disabled=true;btn.textContent='جاري الحفظ...';try{await api(id?'/api/admin/grades/'+id:'/api/admin/grades',{method:id?'PUT':'POST',body:JSON.stringify({name:$("#n").value.trim(),stage:$("#s").value})});closeModal();await load();tab('grades');toast(id?'تم تعديل الصف بنجاح ✓':'تمت إضافة الصف بنجاح ✓')}catch(x){toast(x.message,'error');btn.disabled=false;btn.textContent='حفظ الصف ✓'}}
function openUnit(){openModal(`<div class="modalHead"><span class="bigIcon">📚</span><div><h2>إضافة وحدة</h2><p class="muted">اربط الوحدة بصف محدد.</p></div></div><form onsubmit="saveUnit(event)">${gradeSelect()}<label>اسم الوحدة<input id="n" placeholder="مثال: الوحدة الأولى" required maxlength="100"></label><label>الوصف<textarea id="d" rows="3" placeholder="وصف مختصر للوحدة"></textarea></label><div class="formActions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button id="saveBtn" class="primaryAction">حفظ الوحدة ✓</button></div></form>`)}
function editUnit(id){const u=units.find(x=>x.id===id);openUnit();setTimeout(()=>{$("#gradeId").value=u.gradeId;$("#n").value=u.name;$("#d").value=u.description||'';$("#modalBody form").onsubmit=e=>saveUnit(e,id)},20)}
async function saveUnit(e,id){e.preventDefault();const btn=$("#saveBtn");btn.disabled=true;try{await api(id?'/api/admin/units/'+id:'/api/admin/units',{method:id?'PUT':'POST',body:JSON.stringify({gradeId:$("#gradeId").value,name:$("#n").value.trim(),description:$("#d").value.trim()})});closeModal();await load();tab('units');toast(id?'تم تعديل الوحدة ✓':'تمت إضافة الوحدة ✓')}catch(x){toast(x.message,'error');btn.disabled=false}}
function openLesson(){openModal(`<div class="modalHead"><span class="bigIcon">📖</span><div><h2>إضافة درس</h2><p class="muted">أضف المحتوى واربط فيديو يوتيوب إن وجد.</p></div></div><form onsubmit="saveLesson(event)">${gradeSelect()}<select id="unitId"><option value="">بدون وحدة</option></select><label>عنوان الدرس<input id="t" placeholder="عنوان الدرس" required maxlength="150"></label><label>الملخص<input id="s" placeholder="ملخص سريع للطالب"></label><div class="ytPicker"><label>🎬 فيديو يوتيوب</label><div class="inline"><input id="yt" placeholder="الصق رابط الفيديو أو Video ID"><button type="button" onclick="openYouTubePicker()">اختيار من القناة</button></div><input id="ytt" placeholder="عنوان الفيديو (اختياري)"><div id="ytPreview"></div></div><label>محتوى الدرس<textarea id="c" rows="8" placeholder="اكتب شرح الدرس هنا..."></textarea></label><div class="formActions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button id="saveBtn" class="primaryAction">حفظ الدرس ✓</button></div></form>`);$("#gradeId").onchange=()=>fillUnits($("#gradeId").value);fillUnits(grades[0]?.id||'')}
function fillUnits(g){$("#unitId").innerHTML='<option value="">بدون وحدة</option>'+units.filter(u=>u.gradeId===g).map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('')}
function editLesson(id){const l=lessons.find(x=>x.id===id);openLesson();setTimeout(()=>{$("#gradeId").value=l.gradeId;fillUnits(l.gradeId);$("#unitId").value=l.unitId||'';$("#t").value=l.title;$("#s").value=l.summary||'';$("#c").value=l.content||'';$("#yt").value=l.youtubeId||'';$("#ytt").value=l.youtubeTitle||'';$("#modalBody form").onsubmit=e=>saveLesson(e,id)},20)}
async function saveLesson(e,id){e.preventDefault();const btn=$("#saveBtn");btn.disabled=true;btn.textContent='جاري الحفظ...';try{await api(id?'/api/admin/lessons/'+id:'/api/admin/lessons',{method:id?'PUT':'POST',body:JSON.stringify({gradeId:$("#gradeId").value,unitId:$("#unitId").value||null,title:$("#t").value.trim(),summary:$("#s").value.trim(),content:$("#c").value,youtubeId:$("#yt").value.trim(),youtubeTitle:$("#ytt").value.trim()})});closeModal();await load();tab('lessons');toast(id?'تم تعديل الدرس ✓':'تمت إضافة الدرس ✓')}catch(x){toast(x.message,'error');btn.disabled=false;btn.textContent='حفظ الدرس ✓'}}
async function openYouTubePicker(){const box=$("#ytPreview");box.innerHTML='<div class="notice">⏳ جاري تحميل فيديوهات القناة...</div>';try{const d=await api('/api/youtube/videos?max=30');if(!d.videos?.length){box.innerHTML='<div class="notice">لا توجد فيديوهات متاحة من YouTube API حاليًا.</div>';return}box.innerHTML='<div class="ytGrid">'+d.videos.map(v=>`<button type="button" class="ytCard" data-vid="${esc(v.videoId)}" data-title="${esc(v.title)}"><img src="${esc(v.thumbnail)}" alt=""><b>${esc(v.title)}</b><small>${v.publishedAt?new Date(v.publishedAt).toLocaleDateString('ar-EG'):''}</small></button>`).join('')+'</div>';$$('.ytCard').forEach(b=>b.onclick=()=>pickYouTube(b.dataset.vid,b.dataset.title))}catch(e){box.innerHTML='<div class="notice">'+esc(e.message||'تعذر تحميل الفيديوهات')+'</div>'}}
function pickYouTube(id,title){$("#yt").value=id;$("#ytt").value=title;$("#ytPreview").innerHTML='<div class="successNote">✓ تم اختيار الفيديو وسيتم ربطه بالدرس عند الحفظ.</div>'}
function qEditor(q={}){return `<div class="question"><div class="questionTitle"><b>سؤال</b><button type="button" class="danger mini" onclick="this.closest('.question').remove()">حذف</button></div><input class="qt" placeholder="اكتب السؤال" value="${esc(q.text||'')}" required><input class="qo" placeholder="اختيار 1" value="${esc(q.options?.[0]||'')}" required><input class="qo" placeholder="اختيار 2" value="${esc(q.options?.[1]||'')}" required><input class="qo" placeholder="اختيار 3" value="${esc(q.options?.[2]||'')}" required><input class="qo" placeholder="اختيار 4" value="${esc(q.options?.[3]||'')}" required><select class="qa"><option value="0" ${q.answer===0?'selected':''}>الإجابة الصحيحة: 1</option><option value="1" ${q.answer===1?'selected':''}>الإجابة الصحيحة: 2</option><option value="2" ${q.answer===2?'selected':''}>الإجابة الصحيحة: 3</option><option value="3" ${q.answer===3?'selected':''}>الإجابة الصحيحة: 4</option></select></div>`}
function openQuiz(q=null){openModal(`<div class="modalHead"><span class="bigIcon">📝</span><div><h2>${q?'تعديل':'إضافة'} اختبار</h2><p class="muted">اضبط الوقت ونسبة النجاح وأضف الأسئلة.</p></div></div><form onsubmit="saveQuiz(event,${q?`'${q.id}'`:'null'})">${gradeSelect()}<select id="lessonId"><option value="">بدون درس</option></select><label>اسم الاختبار<input id="t" value="${esc(q?.title||'')}" placeholder="مثال: اختبار الوحدة الأولى" required maxlength="150"></label><div class="row"><label>مدة الاختبار بالدقائق<input id="dur" type="number" min="0" max="300" value="${q?.duration||0}"></label><label>نسبة النجاح %<input id="pass" type="number" min="0" max="100" value="${q?.passingScore??50}"></label></div><div id="qs">${(q?.questions||[{}]).map(qEditor).join('')}</div><button type="button" class="secondary" onclick="$('#qs').insertAdjacentHTML('beforeend',qEditor({}))">＋ إضافة سؤال</button><div class="formActions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button id="saveBtn" class="primaryAction">حفظ الاختبار ✓</button></div></form>`);$("#gradeId").onchange=()=>fillLessons($("#gradeId").value);fillLessons(grades[0]?.id||'');if(q)setTimeout(()=>{$("#gradeId").value=q.gradeId;fillLessons(q.gradeId);$("#lessonId").value=q.lessonId||''},20)}
function fillLessons(g){$("#lessonId").innerHTML='<option value="">بدون درس</option>'+lessons.filter(l=>l.gradeId===g).map(l=>`<option value="${esc(l.id)}">${esc(l.title)}</option>`).join('')}
function editQuiz(id){openQuiz(quizzes.find(q=>q.id===id))}
async function saveQuiz(e,id){e.preventDefault();const questions=$$('#qs .question').map(q=>({text:q.querySelector('.qt').value.trim(),options:[...q.querySelectorAll('.qo')].map(x=>x.value.trim()),answer:Number(q.querySelector('.qa').value)}));if(!questions.length){toast('أضف سؤالًا واحدًا على الأقل','error');return}const btn=$("#saveBtn");btn.disabled=true;try{await api(id?'/api/admin/quizzes/'+id:'/api/admin/quizzes',{method:id?'PUT':'POST',body:JSON.stringify({gradeId:$("#gradeId").value,lessonId:$("#lessonId").value||null,title:$("#t").value.trim(),duration:Number($("#dur").value)||0,passingScore:Math.min(100,Math.max(0,Number($("#pass").value)||0)),questions})});closeModal();await load();tab('quizzes');toast(id?'تم تعديل الاختبار ✓':'تمت إضافة الاختبار ✓')}catch(x){toast(x.message,'error');btn.disabled=false}}
async function deleteGrade(id){if(!confirm('حذف الصف سيحذف الوحدات والدروس والاختبارات المرتبطة به. هل تريد المتابعة؟'))return;await delEntity('/api/admin/grades/'+id,'الصف')}
async function delEntity(u,name){if(!confirm(`هل تريد حذف ${name}؟`))return;try{await api(u,{method:'DELETE'});await load();toast(`تم حذف ${name} ✓`)}catch(x){toast(x.message,'error')}}
function openTeacher(){openModal(`<div class="modalHead"><span class="bigIcon">👨‍🏫</span><div><h2>إضافة مدرس</h2><p class="muted">أنشئ حساب مدرس جديد لإدارة المحتوى.</p></div></div><form onsubmit="saveTeacher(event)"><label>اسم المدرس<input id="n" placeholder="الاسم" required></label><label>البريد الإلكتروني<input id="e" type="email" placeholder="name@example.com" required></label><label>كلمة المرور<input id="p" type="password" minlength="8" placeholder="8 أحرف على الأقل" required></label>${gradeSelect('g',false)}<div class="formActions"><button type="button" class="secondary" onclick="closeModal()">إلغاء</button><button id="saveBtn" class="primaryAction">إنشاء الحساب ✓</button></div></form>`)}
async function saveTeacher(e){e.preventDefault();const btn=$("#saveBtn");btn.disabled=true;try{await api('/api/admin/teachers',{method:'POST',body:JSON.stringify({name:$("#n").value.trim(),email:$("#e").value.trim(),password:$("#p").value,gradeId:$("#g").value||null})});closeModal();await load();tab('users');toast('تم إنشاء حساب المدرس ✓')}catch(x){toast(x.message,'error');btn.disabled=false}}
async function boot(){try{me=await api('/api/me');if(!['admin','teacher'].includes(me.role))throw Error('لا توجد صلاحية إدارة');$("#adminWelcome").textContent=`مرحبًا ${me.name} — ${me.role==='admin'?'مدير المنصة':'مدرس'}`;if(me.role!=='admin')$("#usersTab").classList.add('hidden');await load();tab('dashboard')}catch(e){document.body.innerHTML=`<main><div class="card"><h2>لا توجد صلاحية للدخول</h2><p class="muted">${esc(e.message)}</p><button onclick="parent.openLogin()">تسجيل الدخول</button></div></main>`}}
boot();
