function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}let token=localStorage.getItem("mostakshef_token"),me=null,grades=[],lessons=[],quizzes=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function H(){return {"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})}}
async function api(u,o={}){let r=await fetch(u,{...o,headers:{...H(),...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"حدث خطأ");return d}
function go(v){$$(".view").forEach(x=>x.classList.toggle("hidden",x.id!==v)); if(v==="grades")renderGrades();if(v==="lessons")renderLessons();if(v==="quizzes")renderQuizzes();if(v==="dashboard")renderDash();window.scrollTo(0,0)}
$$("[data-view]").forEach(b=>b.onclick=()=>go(b.dataset.view));
function openModal(x){$("#modalBody").innerHTML=x;$("#modal").classList.remove("hidden")}function closeModal(){$("#modal").classList.add("hidden")}
function openLogin(){openModal(`<h2>تسجيل الدخول</h2><form id="lf"><input id="le" type="email" placeholder="البريد الإلكتروني" required><input id="lp" type="password" placeholder="كلمة المرور" required><button>دخول</button></form>`);$("#lf").onsubmit=login}
function openRegister(){openModal(`<h2>إنشاء حساب طالب</h2><form id="rf"><input id="rn" placeholder="الاسم" required><input id="re" type="email" placeholder="البريد الإلكتروني" required><input id="rp" type="password" minlength="8" placeholder="كلمة المرور (8 أحرف على الأقل)" required><select id="rg">${grades.map(g=>`<option value="${g.id}">${g.name}</option>`).join("")}</select><button>إنشاء الحساب</button></form>`);$("#rf").onsubmit=register}
async function login(e){e.preventDefault();try{let d=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("#le").value,password:$("#lp").value})});token=d.token;localStorage.setItem("mostakshef_token",token);await boot();closeModal()}catch(x){alert(x.message)}}
async function register(e){e.preventDefault();try{let d=await api("/api/register",{method:"POST",body:JSON.stringify({name:$("#rn").value,email:$("#re").value,password:$("#rp").value,gradeId:$("#rg").value})});token=d.token;localStorage.setItem("mostakshef_token",token);await boot();closeModal()}catch(x){alert(x.message)}}
function authArea(){if(!me){$("#authArea").innerHTML='<button onclick="openLogin()">دخول</button><button class="secondary" onclick="openRegister()">إنشاء حساب</button>';$("#adminNav").classList.add("hidden");return}$("#authArea").innerHTML=`<span>مرحبًا، ${me.name}</span><button onclick="logout()">خروج</button>`;$("#adminNav").classList.toggle("hidden",!["admin","teacher"].includes(me.role))}
function logout(){localStorage.removeItem("mostakshef_token");token=null;me=null;authArea();go("home")}
function gradeOptions(sel){return '<option value="">كل الصفوف</option>'+grades.map(g=>`<option value="${g.id}">${g.name}</option>`).join("")}
function renderGrades(){const html=grades.map(g=>`<article class="card"><div class="icon">🎓</div><h3>${g.name}</h3><p>${g.stage==="primary"?"المرحلة الابتدائية":"المرحلة الإعدادية"}</p><button onclick="filterLessons('${g.id}')">استكشف الدروس</button></article>`).join("");$("#allGrades").innerHTML=html}
function filterLessons(g){go("lessons");$("#lessonGrade").value=g;renderLessons()}
function renderLessons(){let g=$("#lessonGrade").value,term=(($("#lessonSearch")?.value)||"").trim().toLowerCase(),a=lessons.filter(l=>(!g||l.gradeId===g)&&(!term||`${l.title} ${l.summary||""}`.toLowerCase().includes(term)));$("#lessonCards").innerHTML=a.length?a.map(l=>`<article class="card"><span class="tag">${gradeName(l.gradeId)}</span><h3>${l.title}</h3><p>${l.summary||""}</p><button onclick="openLesson('${l.id}')">فتح الدرس</button></article>`).join(""):"<div class='notice'>لا توجد دروس لهذا الصف حاليًا.</div>"}
function renderQuizzes(){let g=$("#quizGrade").value,a=quizzes.filter(q=>!g||q.gradeId===g);$("#quizCards").innerHTML=a.length?a.map(q=>`<article class="card"><span class="tag">${gradeName(q.gradeId)}</span><h3>${q.title}</h3><p>${q.questions.length} سؤال</p><button onclick="startQuiz('${q.id}')">ابدأ الاختبار</button></article>`).join(""):"<div class='notice'>لا توجد اختبارات لهذا الصف حاليًا.</div>"}
function gradeName(id){return grades.find(g=>g.id===id)?.name||"—"}
async function openLesson(id){let l=lessons.find(x=>x.id===id);let video=l.youtubeId?`<div class="videoWrap"><iframe src="https://www.youtube.com/embed/${encodeURIComponent(l.youtubeId)}" title="${l.youtubeTitle||l.title}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>`:"";openModal(`<span class="tag">${gradeName(l.gradeId)}</span><h2>${l.title}</h2><p>${l.summary||""}</p>${video}<div class="lessonContent">${(l.content||"لا يوجد محتوى بعد.").replace(/\n/g,"<br>")}</div>${me?`<button onclick="complete('${id}')">✓ تم إنهاء الدرس</button>`:'<div class="notice">سجّل الدخول لحفظ تقدمك.</div>'}`)}
async function complete(id){try{await api("/api/progress",{method:"POST",body:JSON.stringify({lessonId:id,completed:true})});me=await api("/api/me");closeModal();renderDash();alert("تم حفظ تقدمك")}catch(x){alert(x.message)}}
async function startQuiz(id){if(!me){openLogin();return}let q=await api("/api/quizzes/"+id);let startedAt=new Date().toISOString();let timer=null;openModal(`<h2>${q.title}</h2>${q.duration?`<div class="timer" id="timer">الوقت: ${q.duration}:00</div>`:""}<form id="qf">${q.questions.map((x,i)=>`<div class="question"><b>${i+1}. ${x.text}</b>${x.options.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${o}</label>`).join("")}</div>`).join("")}<button>إرسال الإجابات</button></form>`);if(q.duration){let end=Date.now()+q.duration*60000;timer=setInterval(()=>{let sec=Math.max(0,Math.ceil((end-Date.now())/1000));$("#timer").textContent="الوقت: "+Math.floor(sec/60)+":"+String(sec%60).padStart(2,"0");if(sec===0){clearInterval(timer);$("#qf").requestSubmit()}},250)}
$("#qf").onsubmit=async e=>{e.preventDefault();let a=q.questions.map((_,i)=>Number(document.querySelector('input[name="q'+i+'"]:checked').value));try{if(timer)clearInterval(timer);let r=await api("/api/quizzes/"+id+"/submit",{method:"POST",body:JSON.stringify({answers:a,startedAt})});openModal(`<h2>${r.passed?"أحسنت! 🎉":"راجع الدرس وحاول مرة أخرى"}</h2><div class="result">${r.score} / ${r.total}</div><p>نسبتك: ${r.percent}% — ${r.passed?"ناجح":"لم تصل لنسبة النجاح"}</p><button onclick="closeModal();go('dashboard')">عرض تقدمي</button>`);me=await api("/api/me")}catch(x){alert(x.message)}}}
async function renderLeaderboard(){try{const rows=await api('/api/leaderboard');const box=$("#leaderboard");if(!box)return;box.innerHTML=rows.length?rows.map((r,i)=>`<div class="leader"><span>#${i+1}</span><b>${escapeHtml(r.name)}</b><small>${r.points} نقطة</small></div>`).join(""):"<p class='muted'>لا يوجد ترتيب بعد.</p>"}catch(e){}}
function certificate(){if(!me)return;const done=lessons.filter(l=>l.gradeId===me.gradeId&&me.progress?.[l.id]).length,total=lessons.filter(l=>l.gradeId===me.gradeId).length;if(!total||done<total){alert(`الشهادة تظهر بعد إكمال جميع دروس صفك (${done}/${total}).`);return}const w=window.open('','_blank');w.document.write(`<html dir="rtl"><head><title>شهادة إتمام - ${escapeHtml(me.name)}</title><style>body{font-family:Arial;text-align:center;padding:80px;background:#f7f8fa}.cert{border:12px solid #222;padding:70px;background:#fff;max-width:850px;margin:auto}.name{font-size:42px;font-weight:700;margin:30px}.small{font-size:20px}</style></head><body><div class="cert"><h1>شهادة إتمام</h1><p class="small">تشهد منصة مستكشف التعليمية بأن</p><div class="name">${escapeHtml(me.name)}</div><p class="small">أتم دروس مادة الدراسات الاجتماعية للصف ${escapeHtml(gradeName(me.gradeId))}</p><p class="small">التاريخ: ${new Date().toLocaleDateString('ar-EG')}</p><button onclick="print()">طباعة الشهادة</button></div></body></html>`);w.document.close()}
function renderDash(){if(!me){$("#studentDash").innerHTML='<div class="card"><h2>سجّل الدخول أولًا</h2><button onclick="openLogin()">تسجيل الدخول</button></div>';return}let ownLessons=lessons.filter(l=>l.gradeId===me.gradeId),done=ownLessons.filter(l=>me.progress?.[l.id]).length,att=me.attempts||[],pct=ownLessons.length?Math.round(done/ownLessons.length*100):0;$("#studentDash").innerHTML=`<div class="stats"><div class="stat">نسبة الإنجاز<b>${pct}%</b></div><div class="stat">الدروس المكتملة<b>${done}/${ownLessons.length}</b></div><div class="stat">الاختبارات<b>${att.length}</b></div></div><div class="card"><h2>${escapeHtml(me.name)}</h2><p>${escapeHtml(me.email)}</p><div class="progress"><i style="width:${pct}%"></i></div><div class="inline"><button onclick="certificate()">🏆 الشهادة</button></div><h3>آخر النتائج</h3>${att.length?att.slice(-5).reverse().map(a=>`<p>النتيجة: <b>${a.score}/${a.total}</b> — ${a.percent}%</p>`).join(""):"<p class='muted'>لم تؤدِّ اختبارات بعد.</p>"}</div><div class="card"><h3>🏅 الترتيب</h3><div id="leaderboard" class="leaders">جاري التحميل...</div></div>`;renderLeaderboard()}
async function boot(){try{let cfg=await api("/api/site-config");$("#ytChannel").href=cfg.youtubeChannel;grades=await api("/api/grades");lessons=await api("/api/lessons");quizzes=await api("/api/quizzes");if(token)me=await api("/api/me")}catch(e){token=null;localStorage.removeItem("mostakshef_token")}$("#homeGrades").innerHTML=grades.map(g=>`<article class="card"><div class="icon">🗺️</div><h3>${g.name}</h3><button onclick="filterLessons('${g.id}')">ابدأ</button></article>`).join("");$("#lessonGrade").innerHTML=gradeOptions();$("#quizGrade").innerHTML=gradeOptions();$("#lessonGrade").onchange=renderLessons;$("#quizGrade").onchange=renderQuizzes;authArea();renderGrades();renderLessons();renderQuizzes();renderDash()}
boot()
